### ISSUE TITLE
Add upload duplicate detection

### ISSUE THREAD

**Issue by Freshchris01** [yss14/musicshare#1509]
As a user, I want to be informed, when I upload a track, which I already uploaded.
This is very handy for bigger libraries.

**Comment by yss14** [comment]
How would duplicate detection look like?
Only check for file hash?

**Comment by Freshchris01** [comment]
As a first approach, that sounds good.

Hashes aren't stored, right? So to do create the hashes, we need to download all the tracks?

**Comment by yss14** [comment]
Yes, unfortunately we don't store hashes so far.
If we plan to implement this feature during the beta, I think we will find some way to process all already uploaded files and insert the according hashes into the database.

**Comment by yss14** [comment]
Implemented by #1523, #1530, already deployed to beta.
